apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
rules:
  - apiGroups: ["postgres.operator.superkooka.com"]
    resources:
      - databaseclaims
      - databaseclaims/status
      - postgresinstances
      - postgresinstances/status
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "secrets", "events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operator.serviceAccount.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.serviceAccount.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccount.name }}
    namespace: {{ .Values.operator.namespace }}