apiVersion: v2
name: light-k8s-postgres-operator
description: Kubernetes operator for managing PostgreSQL databases
type: application
version: 1.0.0-alpha.2
appVersion: "1.0.0-alpha.2"

dependencies:
  - name: postgresql
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    alias: postgresql
