operator:
  image:
    tag: "early-dev"  # managed-by-gradle
    pullPolicy: Never
  leaderElection: false

postgres:
  enabled: true
  storage:
    type: emptyDir
  credentials:
    password: localdevpassword
