operator:
  image:
    repository: light-k8s-postgres-operator
    tag: "early-dev"  # managed-by-gradle
    pullPolicy: Never
  leaderElection: false

postgresql:
  enabled: true
  storage:
    type: emptyDir
  auth:
    postgresPassword: "local"
