operator:
  image:
    repository: ghcr.io/superkooka/light-k8s-postgres-operator
    tag: "v1.0.0-alpha.1"
    pullPolicy: IfNotPresent
    pullSecrets: []
  # healthPort: 8080
  # metricsPort: 8081
  # leaderElection: false
  namespace: default
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 100m
  serviceAccount:
    name: light-k8s-postgres-operator

postgresql:
  enabled: false
  auth:
    enablePostgresUser: true
    postgresPassword: ""
    existingSecret: ""
    secretKeys:
      adminPasswordKey: postgres-password