name: Renovate

on:
  schedule:
    - cron: "0 4 * * 1" # Every Monday at 4:00 AM UTC
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Renovate token
        id: app-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 #v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@abd08c7549b2a864af5df4a2e369c43f035a6a9d #v46.1.5
        env:
          RENOVATE_TOKEN: ${{ steps.app-token.outputs.token }}
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ALLOWED_UNSAFE_EXECUTIONS: "gradleWrapper"
          RENOVATE_GIT_AUTHOR: "renovate-bot <renovate-bot[bot]@users.noreply.github.com>"